### ISSUE TITLE
V12 + PF2 6.x Compatibility requires a deprecation fix

### ISSUE THREAD

**Issue by apoapostolov** [Frstrm/TokenLightCondition#65]
PF2 changed their API for light in 6.0 and the support needs to be updated. 

```
foundry-esm.js:4617 Error: You are accessing ScenePF2e#darkness which has been migrated to ScenePF2e#environment.darknessLevel
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at logCompatibilityWarning (foundry-esm.js:4605:19)
    at ScenePF2e._logDataFieldMigration (foundry-esm.js:12047:14)
    at ScenePF2e.get (foundry-esm.js:15567:30)
    at Lighting.find_token_lighting (lighting.js:87:35)
    at Lighting.check_token_lighting (lighting.js:63:22)
    at Lighting.check_all_tokens_lightingRefresh (lighting.js:74:30)
    at Core.toggleTokenLightCond (core.js:57:24)
logCompatibilityWarning @ foundry-esm.js:4617
_logDataFieldMigration @ foundry-esm.js:12047
get @ foundry-esm.js:15567
find_token_lighting @ lighting.js:87
check_token_lighting @ lighting.js:63
check_all_tokens_lightingRefresh @ lighting.js:74
toggleTokenLightCond @ core.js:57
await in toggleTokenLightCond (async)
onClick @ main.js:42
_onClickTool @ foundry.js:80893
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry-esm.js:4617 Error: You are accessing ScenePF2e#globalLightThreshold which has been migrated to ScenePF2e#environment.globalLight.darkness.max
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at logCompatibilityWarning (foundry-esm.js:4605:19)
    at ScenePF2e._logDataFieldMigration (foundry-esm.js:12047:14)
    at ScenePF2e.get (foundry-esm.js:15567:30)
    at Lighting.find_token_lighting (lighting.js:90:47)
    at Lighting.check_token_lighting (lighting.js:63:22)
    at Lighting.check_all_tokens_lightingRefresh (lighting.js:74:30)
    at Core.toggleTokenLightCond (core.js:57:24)
logCompatibilityWarning @ foundry-esm.js:4617
_logDataFieldMigration @ foundry-esm.js:12047
get @ foundry-esm.js:15567
find_token_lighting @ lighting.js:90
check_token_lighting @ lighting.js:63
check_all_tokens_lightingRefresh @ lighting.js:74
toggleTokenLightCond @ core.js:57
await in toggleTokenLightCond (async)
onClick @ main.js:42
_onClickTool @ foundry.js:80893
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
lighting.js:197 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'active')
    at Lighting.find_token_lighting (lighting.js:197:24)
    at Lighting.check_token_lighting (lighting.js:63:22)
    at Lighting.check_all_tokens_lightingRefresh (lighting.js:74:30)
    at Core.toggleTokenLightCond (core.js:57:24)
find_token_lighting @ lighting.js:197
check_token_lighting @ lighting.js:63
check_all_tokens_lightingRefresh @ lighting.js:74
toggleTokenLightCond @ core.js:57
await in toggleTokenLightCond (async)
onClick @ main.js:42
_onClickTool @ foundry.js:80893
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:5802 Foundry VTT | Rendering ModuleManagement
foundry.js:7768 Foundry VTT | Retrieved and compiled template templates/setup/parts/package-tags.hbs
foundry.js:7768 Foundry VTT | Retrieved and compiled template templates/sidebar/apps/module-management.html
foundry.js:6323 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at CharacterSheetPF2e.setPosition (foundry.js:6323:27)
    at _onWindowResize (foundry.js:10230:13)
﻿```

**Comment by Frstrm** [comment]
These have been addressed with 0.7.1
